name: word_game
description: "A word game app with Flutter."

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  collection: ^1.18.0
  cross_connectivity: ^3.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  hooks_riverpod: ^2.4.9
  http_parser: ^4.0.2
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  signalr_client_core: ^1.3.8
  web_socket_channel: ^2.4.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
